Add a favicon to the docs and the conda-store server UI
conda-incubator/conda-store pull request #523
Opened 2023-08-03 22:58 UTC by asmeurer

This makes it easier to find conda-store in your Chrome tabs.

2023-08-03 23:13 UTC, asmeurer commented on conda-store-server/conda_store_server/server/static/conda-store-ui/favicon.ico
Is this the correct place to put this file?

2023-08-04 19:23 UTC, costrouc commented on conda-store-server/conda_store_server/server/static/conda-store-ui/favicon.ico
I'd prefer if it were added to just the static path. `conda-store-server/conda_store_server/server/static/favicon.ico`. The conda-store-ui directory things get thrown in there from the hatch build.

2023-08-04 19:24 UTC, costrouc requested changes
Other than that small fix this looks great to me! Thanks @asmeurer. 

Could you rebase this PR on main now? All tests should be passing.

2023-08-08 20:12 UTC, costrouc commented
@asmeurer I force pushed to rebase this PR on `main`.

2023-08-08 20:55 UTC, costrouc approved these changes

2023-08-08 20:55 UTC, merged