[WIP] Sort envs returned by REST API by current build's scheduled_on time
conda-incubator/conda-store pull request #881
Opened 2024-09-17 20:28 UTC by peytondmurray

Fixes #859.

## Description

This PR sorts environments returned when a GET is sent to `/environment/` by the time the environments' current builds were submitted. In systems where users are creating environments while environments are being queried, this ensures that _all_ results are returned; other sorting methods (e.g. by name) can yield incomplete results.

## Pull request checklist

- [x] Did you test this change locally?
- [x] Did you update the documentation (if required)?
- [x] Did you add/update relevant tests for this change (if required)?

2024-10-17 20:20 UTC, peytondmurray commented
After a discussion, it seems like no matter how we solve this there's going to be a breaking change to the API. Cursor-based pagination will allow for any sorting order, so I'll look into implementing that, probably through `fastapi-pagination`.

2024-10-18 23:49 UTC, peytondmurray commented
Adding pagination via `fastapi-pagination` seems simple on the surface, but they don't publish an API reference in the docs, so I'm not sure how it affects what query parameters are accepted by our API. So in the process of trying to implement this, I started working on adding hot reloading, but due to the fact that we're using `traitlets` to load server configuration (and instantiate the FastAPI app) and that `uvicorn` has specific requirements about how the FastAPI app is instantiated when hot reloading, it's trickier to get this working than I thought. See #901 for details.

2024-11-01 23:12 UTC, peytondmurray commented
Hot reloading's done, but the `fastapi_pagination` docs aren't enough to get this working easily, and in the time it would take to actually read through the source for the project I think we can just implement a simple cursor-based paginator instead :/

2025-01-17 06:21 UTC, peytondmurray commented
Not sure if this is actually ready to be merged, as it is not currently compatible with the frontend, and a discussion about REST API versioning needs to be had before this approach can be merged. But otherwise, tests are passing and the implementation is I think mostly complete :) @soapy1

2025-01-17 18:13 UTC, soapy1 requested changes
Looking good! Thank you for adding such beautiful formatted and thorough docs to a lot of these functions :star_struck: 

Just a few things to sort out. 

I took notes on what I tested manually in this gist https://gist.github.com/soapy1/beae935f78725cfd1dd0897c1ce016d4

2025-01-17 18:13 UTC, soapy1 commented on conda-store-server/conda_store_server/_internal/server/views/api.py
> +def get_cursor(cursor: Optional[str] = None) -> Cursor:
Whats the motivation for separating the the `cursor` from the rest of the pagination args?

2025-01-17 18:13 UTC, soapy1 commented on conda-store-server/conda_store_server/_internal/server/views/api.py
> +def get_cursor_paginated_args(
It looks like most of these `depends` type functions are in the [`conda_store_server/_internal/server/dependencies` ](https://github.com/conda-incubator/conda-store/blob/main/conda-store-server/conda_store_server/_internal/server/dependencies.py) module. I think it would be good to consolidate these into that module.

2025-01-17 18:21 UTC, peytondmurray commented on conda-store-server/conda_store_server/_internal/server/views/api.py
> +def get_cursor(cursor: Optional[str] = None) -> Cursor:
There's really no reason other than that the cursor based pagination takes a lot more code than limit/offset, so I've broken that off into a separate module, so that `views/api.py` is mostly endpoints. If it makes more sense to keep this as part of `views/api.py` I'm happy to do so, however.

2025-01-17 18:21 UTC, peytondmurray commented on conda-store-server/conda_store_server/_internal/server/views/api.py
> +def get_cursor_paginated_args(
Totally agree, thank you!

2025-01-17 18:43 UTC, soapy1 commented
One more question (related to how we want to approach versioning for this change): how do we want to approach pagination for the rest of the api? Do we want all the other endpoints to also adopt this type of pagination?

2025-01-17 18:45 UTC, peytondmurray commented
I vote yes - as far as I can tell the advantages of limit/offset are that it's easy to implement, but the cost of it is exactly what is described in #859. Cursor based pagination addresses that.

2025-01-17 19:41 UTC, peytondmurray commented on conda-store-server/conda_store_server/_internal/server/views/api.py
> +        paginated, next_cursor, count = paginate(
The `current_build` field is an optional field in the `Environment` model, so originally I thought there's no harm in allowing it to be returned here unless there's some specific reason to strip it out. Do you think this was intended to make the response smaller?

Anyway, the `current_build_id` is kept here, and FastAPI has a way of excluding fields so I've just made use of that to capture the old behavior.

2025-01-17 20:21 UTC, soapy1 commented on conda-store-server/conda_store_server/_internal/server/views/api.py
> +        paginated, next_cursor, count = paginate(
> Do you think this was intended to make the response smaller?

could be?

2025-01-17 20:34 UTC, peytondmurray commented on conda-store-server/conda_store_server/_internal/server/views/pagination.py
> +                idx = self.order_names.index(order_name)
Ahh, thanks for this - I've added error handling and a test for bad query parameters!

2025-01-22 20:18 UTC, peytondmurray commented
The cursor-based pagination is now on `/api/v2/environment/`, and `/api/v1/environment/` has been restored as well. Ready for a second look!

2025-01-22 21:19 UTC, soapy1 reviewed
Looks great! Just 2 small changes suggested

2025-01-22 21:19 UTC, soapy1 commented on conda-store-server/conda_store_server/_internal/schema.py
> +class APIListEnvironment(APICursorPaginatedResponse):
It looks like the response when I hit the `/v1/environments` api endpoint has changed to

```
$ curl --header "Authorization: bearer ${CS_TOKEN}" http://localhost:8080/conda-store/api/v1/environment/\?size\=2 | jq

. . .
  "status": "ok",
  "message": null,
  "cursor": null,
  "count": 6
}
```

I think this response from the v1 api should be unchanged (wrt to main).  So we'll need to add a new type for the v2 of the api. Something like:

```
class APIV2ListEnvironment(APICursorPaginatedResponse):
     data: List[Environment] = []

class APIListEnvironment(APIPaginatedResponse):
   data: List[Environment]
```

2025-01-22 21:19 UTC, soapy1 commented on conda-store-server/conda_store_server/_internal/server/views/api.py
> +router_api_v2 = APIRouter(
Can the v2 router and associated endpoints go in it's own module (maybe like `api_v2.py`??). I think that'll make it easier to understand that there are multiple living versions of the api and make it easier to make changes in the future.

2025-01-22 21:28 UTC, peytondmurray commented on conda-store-server/conda_store_server/_internal/schema.py
> +class APIListEnvironment(APICursorPaginatedResponse):
You're right - will update now.

2025-01-22 23:18 UTC, soapy1 approved these changes
Looks great :page_with_curl:

2025-01-23 20:12 UTC, merged